### ISSUE TITLE
"R encountered a fatal error" ceScan function

### ISSUE THREAD

**Issue by dpolychr** [ge11232002/CNEr#16]
After running (three times - one setting tFilter and qFilter explicitely to NULL):

cneListDanRer10Hg38 <- ceScan(x=cneDanRer10Hg38,window=windows, identity=identities)

i.e. without the tFilter and qFilter arguments (which can be NULL as stated in the manual), I got the following message:

"R session aborted (R encountered a fatal error. The session was terminated)"

**Comment by ge11232002** [comment]
close by adac92f0a2304367254772c169c2265e58b268c5
