### ISSUE TITLE
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/CNEr/help/CNEr.rdb' is corrupt

### ISSUE THREAD

**Issue by dpolychr** [ge11232002/CNEr#17]
After installing the new dev version of CNEr and running for example:

?CNEDensity 

I get the following error:

Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/CNEr/help/CNEr.rdb' is corrupt

**Comment by ge11232002** [comment]
It has nothing to do with the package itself. Try exit R and load it again.
