### ISSUE TITLE
Rtest error:invalid class “CNE” object: The file `assembly1Fn` must exist!

### ISSUE THREAD

**Issue by fubingting** [ge11232002/CNEr#24]
When I test with cner@1.26.0, the following error occurs：
**test commond：**
Rscript testthat.R
**Error log**
The number of axt files 1
The number of axt alignments is 50
The number of axt files 1
The number of axt alignments is 352
The number of axt files 1
The number of axt alignments is 50
The number of axt files 1
The number of axt alignments is 50
The number of axt files 1
The number of axt alignments is 50
══ Skipped tests ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
● empty test (1)

══ Warnings ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Warning (test_Axt.R:80:3): test_subAxt ──────────────────────────────────────
mustOpen: Can't open /single_sequences.2bit to read: No such file or directory
Backtrace:
 1. CNEr::readAxt(axtFilesHg38DanRer10, tAssemblyFn, qAssemblyFn) test_Axt.R:80:2
 2. CNEr:::seqinfoFn(qAssemblyFn)
 4. rtracklayer::seqinfo(TwoBitFile(fn))
 5. rtracklayer:::.seqlengths_TwoBitFile(x)
── Warning (test_Axt.R:115:3): test_fixCoordinates ─────────────────────────────
mustOpen: Can't open /single_sequences.2bit to read: No such file or directory
Backtrace:
 1. CNEr::readAxt(axtFnDanRer10Hg38, tAssemblyFn = tAssemblyFn, qAssemblyFn = qAssemblyFn) test_Axt.R:115:2
 2. CNEr:::seqinfoFn(tAssemblyFn)
 4. rtracklayer::seqinfo(TwoBitFile(fn))
 5. rtracklayer:::.seqlengths_TwoBitFile(x)
── Warning (test_Axt.R:141:3): test_subAxt ─────────────────────────────────────
mustOpen: Can't open /single_sequences.2bit to read: No such file or directory
Backtrace:
 1. CNEr::readAxt(axtFn, tAssemblyFn, qAssemblyFn) test_Axt.R:141:2
 2. CNEr:::seqinfoFn(tAssemblyFn)
 4. rtracklayer::seqinfo(TwoBitFile(fn))
 5. rtracklayer:::.seqlengths_TwoBitFile(x)
── Warning (test_Axt.R:167:3): test_makeAxtTracks ──────────────────────────────
mustOpen: Can't open /single_sequences.2bit to read: No such file or directory
Backtrace:
 1. CNEr::readAxt(axtFn, tAssemblyFn, qAssemblyFn) test_Axt.R:167:2
 2. CNEr:::seqinfoFn(tAssemblyFn)
 4. rtracklayer::seqinfo(TwoBitFile(fn))
 5. rtracklayer:::.seqlengths_TwoBitFile(x)

══ Failed tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Error (test_Axt.R:80:3): test_subAxt ────────────────────────────────────────
Error: UCSC library operation failed
Backtrace:
    █
 1. └─CNEr::readAxt(axtFilesHg38DanRer10, tAssemblyFn, qAssemblyFn) test_Axt.R:80:2
 2.   └─CNEr:::seqinfoFn(qAssemblyFn)
 3.     ├─GenomeInfoDb::seqinfo(TwoBitFile(fn))
 4.     └─rtracklayer::seqinfo(TwoBitFile(fn))
 5.       └─rtracklayer:::.seqlengths_TwoBitFile(x)
── Error (test_Axt.R:115:3): test_fixCoordinates ───────────────────────────────
Error: UCSC library operation failed
Backtrace:
    █
 1. └─CNEr::readAxt(axtFnDanRer10Hg38, tAssemblyFn = tAssemblyFn, qAssemblyFn = qAssemblyFn) test_Axt.R:115:2
 2.   └─CNEr:::seqinfoFn(tAssemblyFn)
 3.     ├─GenomeInfoDb::seqinfo(TwoBitFile(fn))
 4.     └─rtracklayer::seqinfo(TwoBitFile(fn))
 5.       └─rtracklayer:::.seqlengths_TwoBitFile(x)
── Error (test_Axt.R:141:3): test_subAxt ───────────────────────────────────────
Error: UCSC library operation failed
Backtrace:
    █
 1. └─CNEr::readAxt(axtFn, tAssemblyFn, qAssemblyFn) test_Axt.R:141:2
 2.   └─CNEr:::seqinfoFn(tAssemblyFn)
 3.     ├─GenomeInfoDb::seqinfo(TwoBitFile(fn))
 4.     └─rtracklayer::seqinfo(TwoBitFile(fn))
 5.       └─rtracklayer:::.seqlengths_TwoBitFile(x)
── Error (test_Axt.R:167:3): test_makeAxtTracks ────────────────────────────────
Error: UCSC library operation failed
Backtrace:
    █
 1. └─CNEr::readAxt(axtFn, tAssemblyFn, qAssemblyFn) test_Axt.R:167:2
 2.   └─CNEr:::seqinfoFn(tAssemblyFn)
 3.     ├─GenomeInfoDb::seqinfo(TwoBitFile(fn))
 4.     └─rtracklayer::seqinfo(TwoBitFile(fn))
 5.       └─rtracklayer:::.seqlengths_TwoBitFile(x)
── Error (test_ceScan.R:14:3): test_ceScan ─────────────────────────────────────
Error: there is no package called ‘BSgenome.Drerio.UCSC.danRer10’
Backtrace:
    █
 1. └─base::library(BSgenome.Drerio.UCSC.danRer10) test_ceScan.R:14:2
── Error (test_CNE.R:56:3): test_CNE ───────────────────────────────────────────
Error: invalid class “CNE” object: The file `assembly1Fn` must exist!
Backtrace:
    █
 1. └─CNEr::CNE(...) test_CNE.R:56:2
 2.   └─methods::new(...)
 3.     ├─methods::initialize(value, ...)
 4.     └─methods::initialize(value, ...)
 5.       └─methods::validObject(.Object)

[ FAIL 6 | WARN 4 | SKIP 1 | PASS 69 ]

**Comment by ge11232002** [comment]
You need to have the packages under "SUGGEST" installed to run those tests.
